/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AddressRouteImport } from './routes/address'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersUidRouteImport } from './routes/users.$uid'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { ServerRoute as ApiAuthCallbackGoogleServerRouteImport } from './routes/api/auth/callback/google'

const rootServerRouteImport = createServerRootRoute()

const AddressRoute = AddressRouteImport.update({
  id: '/address',
  path: '/address',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUidRoute = UsersUidRouteImport.update({
  id: '/users/$uid',
  path: '/users/$uid',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackGoogleServerRoute =
  ApiAuthCallbackGoogleServerRouteImport.update({
    id: '/api/auth/callback/google',
    path: '/api/auth/callback/google',
    getParentRoute: () => rootServerRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/address': typeof AddressRoute
  '/auth/login': typeof AuthLoginRoute
  '/users/$uid': typeof UsersUidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/address': typeof AddressRoute
  '/auth/login': typeof AuthLoginRoute
  '/users/$uid': typeof UsersUidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/address': typeof AddressRoute
  '/auth/login': typeof AuthLoginRoute
  '/users/$uid': typeof UsersUidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/address' | '/auth/login' | '/users/$uid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/address' | '/auth/login' | '/users/$uid'
  id: '__root__' | '/' | '/address' | '/auth/login' | '/users/$uid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddressRoute: typeof AddressRoute
  AuthLoginRoute: typeof AuthLoginRoute
  UsersUidRoute: typeof UsersUidRoute
}
export interface FileServerRoutesByFullPath {
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleServerRoute
}
export interface FileServerRoutesByTo {
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/auth/callback/google'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/auth/callback/google'
  id: '__root__' | '/api/auth/callback/google'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAuthCallbackGoogleServerRoute: typeof ApiAuthCallbackGoogleServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/address': {
      id: '/address'
      path: '/address'
      fullPath: '/address'
      preLoaderRoute: typeof AddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$uid': {
      id: '/users/$uid'
      path: '/users/$uid'
      fullPath: '/users/$uid'
      preLoaderRoute: typeof UsersUidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/auth/callback/google': {
      id: '/api/auth/callback/google'
      path: '/api/auth/callback/google'
      fullPath: '/api/auth/callback/google'
      preLoaderRoute: typeof ApiAuthCallbackGoogleServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddressRoute: AddressRoute,
  AuthLoginRoute: AuthLoginRoute,
  UsersUidRoute: UsersUidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthCallbackGoogleServerRoute: ApiAuthCallbackGoogleServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
